[package]
name = "ahorcado"
version = "0.1.0"
authors = ["Fernando Carrascosa <fcarrascosa@fcarrascosa.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.2.0"
rand = "0.7.0"
